### ISSUE TITLE
Timeout Issue

### ISSUE THREAD

**Issue by pmaine** [Bynder/bynder-php-sdk#4]
I receive the following errors when I try to upload an image:

 Fatal error: Uncaught exception 'GuzzleHttp\Exception\ConnectException' with message 'cURL error 7: Failed to connect to bynder-public-us-west-1.s3.amazonaws.com port 443: Timed out (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)' in C:\Bitnami\wampstack-5.6.30-0\apache2\htdocs\bynder\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php on line 186
( ! ) GuzzleHttp\Exception\ConnectException: cURL error 7: Failed to connect to bynder-public-us-west-1.s3.amazonaws.com port 443: Timed out (see http://curl.haxx.se/libcurl/c/libcurl-errors.html) in C:\Bitnami\wampstack-5.6.30-0\apache2\htdocs\bynder\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php on line 186

I believe I am encountering a curl timeout related to  a curl proxy. Please advise.

Thank you

**Comment by noofaq** [comment]
I guess it will be very hard to tell the reason why you experience such exception. I can only confirm that library works well using proxy (as I am using it with the code shown in your other issue) so I would expect that your issue is related either to your implementation or your proxy (it needs to be correctly configured for SSL usage what in general is not that easy). 
I have also noticed that for some proxies (those which are not doing correct SSL pass-through) you need to disable SSL certificate verification in Curl - it is visible in my code as well (of course it reduces security of the connection so it is dissuggested for production environment)

**Comment by jfcsantos** [comment]
Hi there @pmaine , can you give an update on this issue so we can either close it or act on it? 

Cheers
